//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio_Web
{
    public partial class ComprasLista
    {
        protected global::System.Web.UI.WebControls.GridView dgvCompras;
    }
}
