//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio_Web
{
    public partial class ComprasDetalle
    {
        protected global::System.Web.UI.WebControls.Label lblDetalleCompraTitulo;
        protected global::System.Web.UI.WebControls.GridView dgvDetalleCompra;
    }
}
