//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio_Web
{
    public partial class VentasLista
    {
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;
        protected global::System.Web.UI.WebControls.TextBox txtBuscarFactura;
        protected global::System.Web.UI.WebControls.DropDownList ddlCliente;
        protected global::System.Web.UI.WebControls.DropDownList ddlUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
        protected global::System.Web.UI.WebControls.GridView dgvVentas;
        protected global::System.Web.UI.WebControls.Label lblPaginacion;
        protected global::System.Web.UI.WebControls.DropDownList ddlTamanioPagina;
        protected global::System.Web.UI.WebControls.LinkButton btnAnterior;
        protected global::System.Web.UI.WebControls.Repeater rptPaginas;
        protected global::System.Web.UI.WebControls.LinkButton btnSiguiente;
    }
}
