//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio_Web
{
    public partial class VentasFormulario
    {
        protected global::System.Web.UI.WebControls.TextBox txtNumeroFactura;
        protected global::System.Web.UI.WebControls.DropDownList ddlCliente;
        protected global::System.Web.UI.WebControls.Label lblUsuarioVenta;
        protected global::System.Web.UI.WebControls.DropDownList ddlProducto;
        protected global::System.Web.UI.WebControls.TextBox txtCantidad;
        protected global::System.Web.UI.WebControls.TextBox txtPrecio;
        protected global::System.Web.UI.WebControls.Button btnAgregarLinea;
        protected global::System.Web.UI.WebControls.GridView dgvLineas;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
