//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio_Web
{
    public partial class VentasDetalle
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkVolver;
        protected global::System.Web.UI.WebControls.Label lblDetalleVentaTitulo;
        protected global::System.Web.UI.WebControls.Label lblTotalValor;
        protected global::System.Web.UI.WebControls.GridView dgvDetalleVenta;
    }
}
